name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  # Test Backend
  test-backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: server/package-lock.json
    
    - name: Install Backend Dependencies
      working-directory: ./server
      run: npm ci
    
    - name: Lint Backend Code
      working-directory: ./server
      run: npm run lint || echo "No lint script found"
    
    - name: Run Backend Tests
      working-directory: ./server
      run: npm test || echo "No tests found"

  # Test Frontend
  test-frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: client/package-lock.json
    
    - name: Install Frontend Dependencies
      working-directory: ./client
      run: npm ci
    
    - name: Lint Frontend Code
      working-directory: ./client
      run: npm run lint || echo "No lint script found"
    
    - name: Build Frontend
      working-directory: ./client
      run: npm run build
    
    - name: Run Frontend Tests
      working-directory: ./client
      run: npm test || echo "No tests found"

  # Deploy to Production (optional)
  deploy:
    needs: [test-backend, test-frontend]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to Render
      run: |
        echo "Deployment triggered to Render"
        # Add Render deployment webhook here
        # curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
